name: build
on: push
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 3.0
            gemfile: Gemfile
          - ruby: 3.0
            gemfile: gemfiles/Gemfile-7-0
          - ruby: 2.7
            gemfile: gemfiles/Gemfile-6-1
          - ruby: 2.6
            gemfile: gemfiles/Gemfile-6-0
          - ruby: 2.6
            gemfile: gemfiles/Gemfile-5-2
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      USE_OFFICIAL_GEM_SOURCE: 1
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rails test
